# Generated by Django 3.2.20 on 2024-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='completed_cohort',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
